networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring