volumes:
  portainer_data:
    driver: local

services:
  app:
    container_name: portainer-agent
    deploy:
      mode: global
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9443'
      #- '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
