volumes:
  postgres_db:
    driver: local

networks:
  db-net:
    name: db-net
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      LANG: en_US.UTF-8
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
      - 9110:5432/tcp
    networks:
      - db-net